# SonarQube project configuration
sonar.projectKey=MaxLeblc_bobApp
sonar.organization=maxleblc
sonar.host.url=https://sonarcloud.io

# Source files
sonar.sources=back/src/main/java,front/src

# Test files
sonar.tests=back/src/test/java,front/src
sonar.test.inclusions=back/src/test/java/**/*.java,front/src/**/*.spec.ts

# Encoding
sonar.sourceEncoding=UTF-8

# Coverage reports
sonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=front/coverage/bobapp/lcov.info

# Java compiled files
sonar.java.binaries=back/target/classes
